export const FETCHED_CURRENT = "FETCHED_CURRENT";
export const FETCHED_WEEKLY = "FETCHED_WEEKLY";
export const CHANGED_FOCUS = "CHANGED_FOCUS";

export const TOGGLED_UNIT_TYPE = "TOGGLED_UNIT_TYPE";

export const FETCHED_USER_LOCATION = "FETCHED_USER_LOCATION";
export const FETCHED_USER_ZIP = "FETCHED_USER_ZIP";
